const HOME = "http://localhost:8080"

export default {
    adminLogin: () => "/mock/adminLogin.json",
    adminForget: () => "/mock/adminForget.json",
    adminFetchSiderContent: () => "/mock/adminFetchSiderContent.json",
    companyInfo: () =>
        HOME + "/admin/company",
    // "/mock/companyInfo.json",
    alterCompanyInfo: () =>
        HOME + "/admin/company",
    //"/mock/companyInfo.json",
    fetchShop: (uid) =>
        HOME + `/admin/shop/${uid}`,
    // "/mock/shopInfo.json",
    fetchShops: () =>
        HOME + "/admin/shops",
    // "/mock/shopList.json",
    terminalShop: (uid) => HOME + `/admin/shop/${uid}`,
    //"/mock/alterBoxInfo.json",
    fetchClerks: () => HOME + `/admin/clerks`,
    // "/mock/allClerks.json",
    alterBoxInfo: () => "/mock/alterBoxInfo.json",
    removeShopBox: (uid) => HOME + `/admin/shopBox/${uid}`,
    // "/mock/alterBoxInfo.json",
    addBox: () => HOME + "/admin/shopBox",
    // "/mock/addBoxInfo.json",
    alterShopInfo: () => "/mock/alterBoxInfo.json",
    addShop: () => HOME + "/admin/shop",
    // "/mock/addShop.json",
    fetchAllAuthority: () => "/mock/allAuthority.json",
    fetchPositions: () => HOME + "/positions",
    // "/mock/allPosition.json",
    alterClerkInfo: () => "/mock/alterClerkInfo.json",
    terminalClerk: (uid) => HOME + `/admin/clerk/${uid}`,
    // "/mock/alterClerkInfo.json",
    addClerk: () => HOME + "/admin/clerk",
    // "/mock/addClerk.json",
    fetchProductTypes: () => HOME + "/admin/productTypes",
    //  "/mock/productType.json",
    fetchProductDetailByType: () => "/mock/productDetailByType.json",
    fetchCustomerTypes: () => HOME + "/admin/customerTypes",
    // "/mock/customerType.json",
    fetchActivities: () => HOME + "/admin/activities",
    // "/mock/activities.json",
    terminalActivity: (uid) => HOME + `/admin/activity/${uid}`,
    // "/mock/alterBoxInfo.json",
    addActivity: () => HOME + "/admin/activity",
    //"/mock/activities.json",
    addProductType: () => HOME + "/admin/productType",
    // "/mock/productType.json",
    addProduct: () => HOME + "/admin/product",
    // "/mock/productDetailByType.json",
    terminalProductSale: () => "/mock/productDetailByType.json",
    alterProductInfo: () => "/mock/productDetailByType.json",
    fetchEnterpriseCustomerApplication: (isFetchAll) => `${HOME}/admin/enterpriseCustomerApplications/${isFetchAll}`,
    // "/mock/enterpriseCustomerApplication.json",
    startApplicationCheck: (uid) =>`${HOME}/admin/startEnterpriseCustomerApplication/${uid}`,
    //  "/mock/enterpriseCustomerApplication.json",
    approveApplication: (uid) => `${HOME}/admin/approveEnterpriseCustomerApplication/${uid}`,
    // "/mock/enterpriseCustomerApplication.json",
    rejectApplication:  (uid) => `${HOME}/admin/rejectEnterpriseCustomerApplication/${uid}`,
    fetchCustomers: () => `${HOME}/admin/customers`,
    // "/mock/customers.json",
    setSuperVIP: (uid) => `${HOME}/admin/setSupervip/${uid}`,
    // "/mock/customers.json",
    fetchOrdersByCustomer: (uid,timeRange) => `${HOME}/admin/ordersByCustomer/${uid}/${timeRange.startDate}/${timeRange.endDate}`,
    // "/mock/ordersByCustomer.json",
    fetchCustomerById: () => "/mock/customer.json",
    deleteOrder: () => "/mock/ordersByCustomer.json",
    deleteOrderByBatch: () => "/mock/ordersByCustomer.json",
    fetchOrderById: () => "/mock/order.json",
    uploadPhoto: () => HOME + "/admin/savephoto",
    fetchShopBoxes: () => HOME + "/admin/shopBoxes",
    fetchShopBox: (uid) => HOME + `/admin/shopBox/${uid}`,
    updateShopBox: () => HOME + `/admin/shopBox`,
    updateShop: () => HOME + "/admin/shop",
    fetchClerk: (uid) => HOME + `/admin/clerk/${uid}`,
    updateClerk: () => HOME + "/admin/clerk",
    fetchActivitiesNameDesc: () => HOME + "/admin/activitiesNameDesc",
    fetchActivityRuleTypes: () => HOME + "/admin/activityRuleTypes",
    fetchProductsName: () => HOME + `/admin/productsName`,
    fetchActivity: (uid) => HOME + `/admin/activity/${uid}`,
    updateActivity: () => HOME + "/admin/activity",
    fetchProducts: () => HOME + "/admin/products",
    terminalProduct: (uid) => HOME + `/admin/product/${uid}`,
    fetchProduct: (uid) => `${HOME}/admin/product/${uid}`,
    updateProduct: () => `${HOME}/admin/product`,
    fetchApplication:(uid)=>`${HOME}/admin/enterpriseCustomerApplication/${uid}`,
    fetchUncompleteOrders:()=>`${HOME}/admin/uncompleteOrders`,
    fetchOrders:(status,timeRange)=>`${HOME}/admin/orders/${status}/${timeRange.startDate}/${timeRange.endDate}`,
    fetchOrder:(uid)=>`${HOME}/admin/order/${uid}`,
    updateOrderStatus:(status)=>`${HOME}/admin/order${status}`,
    fetchTags:()=>`${HOME}/admin/tags`,
    addTag:()=>`${HOME}/admin/tag`,
    addArticle:()=>`${HOME}/admin/article`,
    fetchArticles:(status,timeRange)=>`${HOME}/admin/articles/${status}/${timeRange.startDate}/${timeRange.endDate}`,
    terminalArticle:(uid)=>`${HOME}/admin/article/${uid}`,
    idPswLogin:()=>`${HOME}/admin/idLogin`,
    sendClerkOtp:(contact)=>`${HOME}/clerkSms?contact=${contact}`,
    otpLogin:(contact,otp)=>`${HOME}/admin/otpLogin?contact=${contact}&otp=${otp}`,
    verifyToken:()=>`${HOME}/verifyToken`,
    savePhoto:()=>`${HOME}/savephoto`,
}